Controllers/BetController.cs
using Auction.Models;
using Microsoft.AspNetCore.Mvc;

namespace Auction.Controllers
{
    public class BetController : Controller
    {
        private readonly DBContext _context;

        public BetController(DBContext context)
        {
            _context = context;
        }

        [HttpGet]
        [Route("/Bet/MakeBet/{id:int}")]
        public IActionResult MakeBet(int id)
        {
            ViewBag.AuctionId = id;
            return View();
        }

        [HttpPost]
        [Route("/Bet/MakeBet/{id:int}")]
        public IActionResult MakeBet(int id, int Amount)
        {
            var auction = _context.Auctions.FirstOrDefault(a => a.Id == id);

            if (auction != null)
            {
                var highestBet = _context.Bets.Where(b => b.AuctionId == id).OrderByDescending(b => b.Amount).FirstOrDefault();
                if (Amount <= auction.StartPrice || (highestBet != null && Amount <= highestBet.Amount))
                {
                    TempData["Error"] = "The bet must be higher compare to previous";
                    return RedirectToAction("Index", "Home");
                }

                if (HttpContext.Session.GetInt32("UserId") == null)
                {
                    TempData["Error"] = "You must login or register";
                }

                else
                {
                    var newBet = new Bet { Amount = Amount, UserId = (int)HttpContext.Session.GetInt32("UserId"), AuctionId = id };
                    _context.Bets.Add(newBet);
                    _context.SaveChanges();
                }

                return RedirectToAction("Index", "Home");
            }
            else
            {
                return View("Error");
            }
        }

    }
}

Controllers/CreateAuctionController.cs
using Auction.Models;
using Microsoft.AspNetCore.Mvc;
using System.Xml.Linq;

namespace Auction.Controllers
{
    public class CreateAuctionController : Controller
    {
        private readonly DBContext _context;

        public CreateAuctionController(DBContext context)
        {
            _context = context;
        }

        [HttpPost]
        public async Task<IActionResult> CreateAuction(Models.Auction model)
        {
            model.UserId = (int)HttpContext.Session.GetInt32("UserId");

            Models.Auction auction = new Models.Auction
            {
                Name = model.Name,
                Description = model.Description,
                StartPrice = model.StartPrice,
                UserId = model.UserId
            };

            _context.Auctions.Add(auction);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index", "Home");
        }
    }
}

Controllers/EditAuctionController.cs
using Auction.Models;
using Microsoft.AspNetCore.Mvc;

namespace Auction.Controllers
{
    public class EditAuctionController : Controller
    {
        private readonly DBContext _context;

        public EditAuctionController(DBContext context)
        {
            _context = context;
        }

        [HttpPost]
        [Route("/EditAuction/EditAuction/{id:int}")]
        public IActionResult EditAuction(int id, string Name, string Description, int StartPrice)
        {
            var auction = _context.Auctions.FirstOrDefault(a => a.Id == id);

            if (auction != null)
            {
                auction.Name = Name;
                auction.Description = Description;
                auction.StartPrice = StartPrice;

                _context.SaveChanges();

                return RedirectToAction("Index", "Home");
            }
            else
            {
                return View("Error");
            }
        }

    }
}

Controllers/LoginController.cs
using Auction.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Auction.Controllers
{
    public class LoginController : Controller
    {
        private readonly DBContext _context;

        public LoginController(DBContext context)
        {
            _context = context;
        }

        [HttpPost]
        public async Task<IActionResult> Login(User model)
        {
            var user = await _context.Users
                .FirstOrDefaultAsync(u => u.Email == model.Email && u.Password == model.Password);

            if (user != null)
            {
                HttpContext.Session.SetInt32("UserId", user.Id);
                return RedirectToAction("Profile", "Profile");
            }

            ViewBag.Error = "Wrong login or password or user not exists";
            return View(model);
        }

    }

}

Controllers/ProfileController.cs
using Auction.Models;
using Microsoft.AspNetCore.Mvc;

namespace Auction.Controllers
{
    public class ProfileController : Controller
    {
        private readonly DBContext _context;

        public ProfileController(DBContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Profile()
        {
            var userId = HttpContext.Session.GetInt32("UserId");
            if (userId.HasValue)
            {
                var user = await _context.Users.FindAsync(userId.Value);
                if (user != null)
                {
                    return View(user);
                }
            }

            return RedirectToAction("Login", "Login");
        }
    }

}

Controllers/ViewAuctionBetsController.cs
using Auction.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Auction.Controllers
{
    public class ViewAuctionBetsController : Controller
    {
        private readonly DBContext _context;

        public ViewAuctionBetsController(DBContext context)
        {
            _context = context;
        }

        [HttpGet]
        [Route("/ViewAuctionBets/ViewAuctionBets/{id:int}")]
        public IActionResult ViewAuctionBets(int id)
        {
            var bets = _context.Bets
                               .Where(b => b.AuctionId == id)
                               .Include(b => b.CreationUser)
                               .ToList();

            return View(bets);
        }
    }
}

Controllers/ViewAuctionController.cs
using Auction.Models;
using Microsoft.AspNetCore.Mvc;

namespace Auction.Controllers
{
    public class ViewAuctionController : Controller
    {
        public IActionResult ViewAuction()
        {
            return View();
        }
    }
}

Pages/Shared/CreateAuction.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Auction.Pages
{
    public class CreateAuctionModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Pages/Shared/EditAuction.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Auction.Pages.Shared
{
    public class EditAuctionModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Pages/Shared/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Auction.Pages
{
    public class ErrorModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Pages/Shared/Login.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Auction.Pages
{
    public class LoginModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Pages/Shared/MakeBet.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Auction.Pages.Shared
{
    public class MakeBetModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Pages/Shared/Profile.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Auction.Pages
{
    public class ProfileModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Pages/Shared/Register.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Auction.Pages
{
    public class RegisterModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Pages/Shared/ViewAuction.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Auction.Pages
{
    public class ViewAuctionModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Pages/Shared/ViewAuctionBets.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Auction.Pages
{
    public class ViewAuctionBetsModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Pages/Shared/CreateAuction.cshtml
@page
@model Auction.Models.Auction

<div class="create-auc-wrapper">
    <h3>СТВОРИТИ АУКЦІОН</h3>
    <div class="create-auc-wrapper-content">
        <form asp-controller="CreateAuction" asp-action="CreateAuction" method="post">
            <h3 class="create-auc-h3">Назва</h3>
            <input asp-for="Name" class="form1-cr-auc" type="text">
            <h3 class="create-auc-h3">Опис</h3>
            <input asp-for="Description" class="form2-cr-auc" type="text">
            <h3 class="create-auc-h3">Стартова ціна</h3>
            <input asp-for="StartPrice" class="form3-cr-auc" type="number">
            <button class="create-auc-btn" type="submit">Зберегти</button>
        </form>
    </div>
</div>

Pages/Shared/EditAuction.cshtml
@page "/EditAuction/EditAuction/{id:int}"
@model Auction.Pages.Shared.EditAuctionModel
@inject Services.IAuctionService AuctionService

@{
    var id = Convert.ToInt32(RouteData.Values["id"]);
    var auction = AuctionService.GetAuctionById(id);
}

<form asp-controller="EditAuction" asp-action="EditAuction" asp-route-id="@auction.Id" method="post">
    <div class="view-auc-wr">
        <h2 class="my-auc view-auc-h2">
            <input class="edit-item" type="text" value="@auction.Name" name="Name" />
        </h2>
        <div class="view-auc-main">
            <div>
                <p class="view-auc-p">
                    <textarea class="edit-item" name="Description">@auction.Description</textarea>
                </p>
                <div class="view-auc-main-cont">
                    <h3 class="view-auc-h3">СТАРТОВА ЦІНА</h3>
                    <span class="view-auc-span">
                        <input class="edit-item" type="number" value="@auction.StartPrice" name="StartPrice" />
                    </span>
                </div>
            </div>
        </div>
        <div class="view-auc-btns">
            <button type="submit" class="v-auc-btn">ЗБЕРЕГТИ</button>
        </div>
    </div>
</form>

Pages/Shared/Index.cshtml
@page
@inject Services.IAuctionService AuctionService

<div class="main-sc-content">
    <h1>АУКЦІОНИ</h1>
    <div class="main-sc-auc-wrapper">
        @foreach (var auction in AuctionService.GetAllAuctions())
        {
            <a asp-controller="ViewAuction" asp-action="ViewAuction" asp-route-id="@auction.Id" class="a-items">
                <div class="main-sc-auc-item">
                    <p class="main-sc-auc-item-h">@auction.Name</p>
                    <div class="main-sc-auc-item-wr">
                        <p class="main-sc-auc-item-pr-p">Початкова ціна: </p>
                        <span class="main-sc-auc-item-pr-sp">@auction.StartPrice</span>
                    </div>
                </div>
            </a>
        }
    </div>
    @if (!string.IsNullOrEmpty(TempData["Error"] as string))
    {
        <script>alert("@TempData["Error"]");</script>
    }
</div>

Pages/Shared/Login.cshtml
@page
@model Auction.Models.User

<div class="reg-wrapper">
    <h3 class="reg-h">ВХІД</h3>
    <form method="post" action="/Login/Login">
        <h3 class="log-txt">Логін</h3>
        <input class="form-reg" type="text" placeholder="Введіть логін" name="Email">
        <h3 class="log-txt">Пароль</h3>
        <input class="form-reg" type="password" placeholder="Введіть пароль" name="Password">
        <div>
            <button class="register-btn" type="submit">Вхід</button>
        </div>
    </form>
    @if (!string.IsNullOrEmpty(ViewBag.Error))
    {
        <script>alert("@ViewBag.Error");</script>
    }
</div>

Pages/Shared/MakeBet.cshtml
@page "/Bet/MakeBet/{id:int}"
@inject Services.IAuctionService AuctionService

@{
    int id = ViewBag.AuctionId;
    Models.Bet bet = AuctionService.GetLatestBet(id);
    string betAmountText;

    if (bet == null)
    {
        betAmountText = "Ще не було ставок";
    }
    else
    {
        betAmountText = bet.Amount.ToString();
    }
}

<form asp-controller="Bet" asp-action="MakeBet" method="post">
<div class="reg-wrapper">
    <h3 class="reg-h">ПОСТАВИТИ СТАВКУ</h3>

        <h3 class="log-txt">Остання ставка</h3>
        <h3 class="log-txt last-bet">@betAmountText</h3>
        <h3 class="log-txt">Ваша ставка</h3>
        <input class="form-reg" type="number" placeholder="Введіть ставку" name="Amount">
        <div>
            <button class="register-btn" type="submit">Зберегти</button>
        </div>

    @if (!string.IsNullOrEmpty(ViewBag.Error))
    {
        <script>alert("@ViewBag.Error");</script>
    }
</div>
</form>

Pages/Shared/Profile.cshtml
@model Auction.Models.User
@inject Services.IAuctionService AuctionService

<div class="profile-wrapper">
    <div class="myinfo">
        <h3 class="profile-h">ПРОФІЛЬ КОРИСТУВАЧА</h3>
        <h4 class="pr-inf">@Model.Name</h4>
        <h4 class="pr-inf">@Model.Email</h4>
    </div>

    <div class="profile-oppor">
        <h3 class="my-auc">МОЇ АУКЦІОНИ</h3>
        <div class="pr-cont-wr">
            <a asp-page="/Shared/CreateAuction" class="create-btn">+</a>

            @foreach (var auction in AuctionService.GetAllAuctionsByOneUser())
            {
                <div class="main-sc-auc-item">
                    <p class="main-sc-auc-item-h">@auction.Name</p>
                    <div class="main-sc-auc-item-wr">
                        <p class="main-sc-auc-item-pr-p">Початкова ціна: </p>
                        <span class="main-sc-auc-item-pr-sp">@auction.StartPrice</span>
                    </div>
                    <div class="pr-edit-btn-wr">
                        <a asp-controller="EditAuction" asp-action="EditAuction" asp-route-id="@auction.Id" class="pr-edit-btn">Редагувати</a>
                    </div>
                </div>
            }
           
        </div>
    </div>
</div>

Pages/Shared/Register.cshtml
@page
@model Auction.Models.User

<div class="reg-wrapper">
    <h2 class="reg-h">РЕЄСТРАЦІЯ</h2>
    <div class="reg-div">
        <form method="post" action="/Registration/Register">
            <h3>Прізвище, Ім'я, По батькові</h3>
            <input class="form-reg" type="text" placeholder="Введіть своє ПІБ" name="Name">
            <h3>Телефон</h3>
            <input class="form-reg" type="text" placeholder="Введіть свій номер" name="PhoneNumber">
            <h3>E-mail</h3>
            <input class="form-reg" type="text" placeholder="Введіть E-mail" name="Email">
            <h3>Пароль</h3>
            <input class="form-reg" type="password" placeholder="Створіть пароль" name="Password">
            <h3>Підтвердження паролю</h3>
            <input class="form-reg" type="password" placeholder="Підтвердіть пароль" name="ConfirmPassword">
            <div>
                <button class="register-btn" type="submit">Зареєструватися</button>
            </div>
        </form>
    </div>
</div>

Pages/Shared/ViewAuction.cshtml
@page "/ViewAuction/ViewAuction/{id:int}"
@model Pages.ViewAuctionModel
@inject Services.IAuctionService AuctionService

@{
    int id = Convert.ToInt32(RouteData.Values["id"]);
    Models.Auction auction = AuctionService.GetAuctionById(id);
    var userId = auction.UserId;
    Models.User user = AuctionService.GetUserById(userId);
}

<div class="view-auc-wr">
    <h2 class="my-auc view-auc-h2">@auction.Name</h2>
    <div class="view-auc-main">
        <div>
            <p class="view-auc-p">
                @auction.Description
            </p>
            <div class="view-auc-main-cont">
                <h3 class="view-auc-h3">СТАРТОВА ЦІНА</h3>
                <span class="view-auc-span">@auction.StartPrice</span>
            </div>
            <div class="view-auc-main-cont">
                <h3 class="view-auc-h3">СТВОРИВ</h3>
                <span class="view-auc-span">@user.Name</span>
            </div>
        </div>
    </div>
    <div class="view-auc-btns">
        <a class="v-auc-btn" asp-controller="ViewAuctionBets" asp-action="ViewAuctionBets" asp-route-id="@auction.Id">ІСТОРІЯ СТАВОК</a>
        <a class="v-auc-btn" asp-controller="Bet" asp-action="MakeBet" asp-route-id="@auction.Id" >ПОСТАВИТИ СТАВКУ</a>
    </div>
</div>

Pages/Shared/ViewAuctionBets.cshtml
@model List<Auction.Models.Bet>

<div class="view-b-wr">
    <h2 class="my-auc view-b-h2">ІСТОРІЯ СТАВОК</h2>
    <div class="view-b-main-cont">
        <div class="view-b-cont">
            @foreach (var bet in Model)
            {
                <div class="view-b-cont-item">
                    <p class="view-b-name">@bet.CreationUser.Name</p>
                    <p class="view-b-name">СТАВКА -></p>
                    <span class="view-b-bet">@bet.Amount</span>
                </div>
            }
        </div>
    </div>
</div>

Pages/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link rel="icon" href="~/assets/logo.svg" type="image/x-icon">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/media.css" asp-append-version="true" />

</head>
<body>
    <header>
        <div class="h-one">
            <a asp-page="/Shared/Index">
                <div>
                    <img src="~/assets/logo_head.svg" class="logo-img" alt="logo" />
                </div>
            </a>
        </div>
        <div class="h-two">
            <a asp-page="/Shared/Index" class="head-def">Усі аукціони</a>
            <a asp-page="/Shared/Login" class="head-def">Вхід</a>
            <a asp-page="/Shared/Register" class="head-reg">Зареєструватися</a>
        </div>
    </header>

    <div class="container">
        <main role="main">
            @RenderBody()
        </main>
    </div>
</body>
</html>